# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestcompletepurchaseworkflow():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testcompletepurchaseworkflow(self):
    self.driver.get("http://127.0.0.1:8080/")
    self.driver.set_window_size(1708, 1020)
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(2) .hot-product-card-img-overlay").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary").click()
    self.driver.find_element(By.LINK_TEXT, "Continue Shopping").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(3) .hot-product-card-img-overlay").click()
    self.driver.find_element(By.ID, "quantity").click()
    dropdown = self.driver.find_element(By.ID, "quantity")
    dropdown.find_element(By.XPATH, "//option[. = '2']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary").click()
    element = self.driver.find_element(By.ID, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "street_address").click()
    self.driver.find_element(By.ID, "street_address").click()
    self.driver.find_element(By.ID, "street_address").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-5").click()
    self.driver.find_element(By.ID, "zip_code").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-5").click()
    self.driver.find_element(By.ID, "zip_code").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cart-sections > .container > .row").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-5").click()
    self.driver.find_element(By.ID, "country").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-row:nth-child(6)").click()
    self.driver.find_element(By.ID, "credit_card_number").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-5").click()
    self.driver.find_element(By.ID, "credit_card_number").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cart-sections > .container > .row").click()
    self.driver.find_element(By.ID, "credit_card_expiration_month").click()
    dropdown = self.driver.find_element(By.ID, "credit_card_expiration_month")
    dropdown.find_element(By.XPATH, "//option[. = 'August']").click()
    self.driver.find_element(By.ID, "credit_card_expiration_year").click()
    dropdown = self.driver.find_element(By.ID, "credit_card_expiration_year")
    dropdown.find_element(By.XPATH, "//option[. = '2025']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Continue Shopping").click()
  
