# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTesterrorhandlingscenarios():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testerrorhandlingscenarios(self):
    self.driver.get("http://127.0.0.1:8080/")
    self.driver.set_window_size(1708, 1020)
    self.driver.find_element(By.CSS_SELECTOR, ".logo").click()
    self.driver.find_element(By.LINK_TEXT, "Continue Shopping").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(2) .hot-product-card-img-overlay").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary").click()
    element = self.driver.find_element(By.ID, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, ".cart-sections").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cart-sections > .container > .row").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("1@1.com")
    self.driver.find_element(By.CSS_SELECTOR, ".cart-sections > .container > .row").click()
    self.driver.find_element(By.ID, "street_address").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Continue Shopping").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(3) .hot-product-card-img-overlay").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-5").click()
    self.driver.find_element(By.ID, "zip_code").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary:nth-child(1)").click()
    self.driver.find_element(By.ID, "zip_code").send_keys("111111")
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary:nth-child(1)").click()
    self.driver.find_element(By.ID, "zip_code").send_keys("1111111")
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary:nth-child(1)").click()
    self.driver.find_element(By.ID, "zip_code").send_keys("11111111")
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cart-sections > .container > .row").click()
    self.driver.find_element(By.ID, "zip_code").click()
    self.driver.find_element(By.ID, "zip_code").send_keys("97123")
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Continue Shopping").click()
    self.driver.find_element(By.CSS_SELECTOR, ".logo").click()
    self.driver.find_element(By.LINK_TEXT, "Continue Shopping").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(4) .hot-product-card-img-overlay").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cart-sections > .container > .row").click()
    self.driver.find_element(By.ID, "credit_card_number").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-row:nth-child(8) > .col").click()
    self.driver.find_element(By.ID, "credit_card_number").click()
    self.driver.find_element(By.ID, "credit_card_number").click()
    self.driver.find_element(By.ID, "credit_card_number").click()
    self.driver.find_element(By.ID, "credit_card_number").click()
    self.driver.find_element(By.ID, "credit_card_number").send_keys("1111111111111111")
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".logo").click()
    self.driver.find_element(By.ID, "credit_card_cvv").click()
    self.driver.find_element(By.ID, "credit_card_cvv").click()
    self.driver.find_element(By.ID, "credit_card_cvv").click()
    self.driver.find_element(By.ID, "credit_card_cvv").send_keys("asv")
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary:nth-child(1)").click()
    self.driver.find_element(By.ID, "credit_card_cvv").send_keys("asv.")
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-form-field:nth-child(3)").click()
    self.driver.find_element(By.ID, "credit_card_cvv").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, ".cymbal-button-primary:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Continue Shopping").click()
  
