# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTesthomepagebrowsing():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testhomepagebrowsing(self):
    self.driver.get("http://127.0.0.1:8080/")
    self.driver.set_window_size(1708, 1020)
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(2) .hot-product-card-img-overlay").click()
    self.driver.find_element(By.CSS_SELECTOR, ".top-left-logo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(3) .hot-product-card-img-overlay").click()
    self.driver.find_element(By.CSS_SELECTOR, ".top-left-logo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(4) .hot-product-card-img-overlay").click()
    self.driver.find_element(By.CSS_SELECTOR, ".justify-content-between").click()
    self.driver.find_element(By.CSS_SELECTOR, ".top-left-logo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(5) .hot-product-card-img-overlay").click()
    self.driver.find_element(By.CSS_SELECTOR, ".top-left-logo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(6) .hot-product-card-img-overlay").click()
    self.driver.find_element(By.CSS_SELECTOR, ".top-left-logo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(7) .hot-product-card-img-overlay").click()
    self.driver.find_element(By.CSS_SELECTOR, ".top-left-logo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(8) .hot-product-card-img-overlay").click()
    self.driver.find_element(By.CSS_SELECTOR, ".top-left-logo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(6) .hot-product-card-img-overlay").click()
    self.driver.find_element(By.CSS_SELECTOR, ".top-left-logo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(7) .hot-product-card-img-overlay").click()
    self.driver.find_element(By.CSS_SELECTOR, ".top-left-logo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(5) .hot-product-card-img-overlay").click()
    self.driver.find_element(By.CSS_SELECTOR, ".top-left-logo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(6) .hot-product-card-img-overlay").click()
    self.driver.find_element(By.CSS_SELECTOR, ".top-left-logo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(7) .hot-product-card-img-overlay").click()
    self.driver.find_element(By.CSS_SELECTOR, "main").click()
    self.driver.find_element(By.CSS_SELECTOR, ".top-left-logo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(2) .hot-product-card-img-overlay").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(1) img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(2) img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(3) img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(4) img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".top-left-logo").click()
    self.driver.find_element(By.NAME, "currency_code").click()
    dropdown = self.driver.find_element(By.NAME, "currency_code")
    dropdown.find_element(By.XPATH, "//option[. = 'GBP']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".arrow").click()
    self.driver.find_element(By.CSS_SELECTOR, ".arrow").click()
    self.driver.find_element(By.NAME, "currency_code").click()
    dropdown = self.driver.find_element(By.NAME, "currency_code")
    dropdown.find_element(By.XPATH, "//option[. = 'EUR']").click()
    self.driver.find_element(By.NAME, "currency_code").click()
    dropdown = self.driver.find_element(By.NAME, "currency_code")
    dropdown.find_element(By.XPATH, "//option[. = 'CAD']").click()
    self.driver.find_element(By.NAME, "currency_code").click()
    dropdown = self.driver.find_element(By.NAME, "currency_code")
    dropdown.find_element(By.XPATH, "//option[. = 'JPY']").click()
    self.driver.find_element(By.NAME, "currency_code").click()
    dropdown = self.driver.find_element(By.NAME, "currency_code")
    dropdown.find_element(By.XPATH, "//option[. = 'USD']").click()
    self.driver.find_element(By.NAME, "currency_code").click()
    self.driver.find_element(By.NAME, "currency_code").click()
  
