# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestuserlogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testuserlogin(self):
    self.driver.get("http://127.0.0.1:8080/index.html")
    self.driver.set_window_size(1050, 746)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    element = self.driver.find_element(By.LINK_TEXT, "Login")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "username-modal").click()
    self.driver.find_element(By.ID, "username-modal").send_keys("testuser123")
    self.driver.find_element(By.ID, "password-modal").click()
    self.driver.find_element(By.ID, "password-modal").send_keys("password123")
    self.driver.find_element(By.ID, "password-modal").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "username-modal").send_keys("testuser123")
    self.driver.find_element(By.ID, "password-modal").send_keys("password123")
    self.driver.find_element(By.ID, "register-username-modal").send_keys("testuser123")
    self.driver.find_element(By.ID, "register-password-modal").send_keys("password123")
  
