# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestuserregistration():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testuserregistration(self):
    self.driver.get("http://127.0.0.1:8080/")
    self.driver.set_window_size(1048, 745)
    self.driver.find_element(By.LINK_TEXT, "Register").click()
    element = self.driver.find_element(By.LINK_TEXT, "Register")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "register-username-modal").click()
    self.driver.find_element(By.ID, "register-username-modal").send_keys("testuser123")
    self.driver.find_element(By.ID, "register-first-modal").click()
    self.driver.find_element(By.ID, "register-first-modal").send_keys("Test")
    self.driver.find_element(By.ID, "register-last-modal").click()
    self.driver.find_element(By.ID, "register-last-modal").send_keys("User")
    self.driver.find_element(By.ID, "register-email-modal").click()
    self.driver.find_element(By.ID, "register-email-modal").send_keys("testuser123@example.com")
    self.driver.find_element(By.ID, "register-password-modal").click()
    self.driver.find_element(By.ID, "register-password-modal").send_keys("password123")
    self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(6) > .btn").click()
  
