# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestcompleteshoppingworkflow():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testcompleteshoppingworkflow(self):
    self.driver.get("http://127.0.0.1:8080/index.html")
    self.driver.set_window_size(1048, 746)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    element = self.driver.find_element(By.LINK_TEXT, "Login")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "login-modal").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(3) .fa").click()
    self.driver.find_element(By.LINK_TEXT, "Catalogue").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox:nth-child(1) input").click()
    self.driver.find_element(By.LINK_TEXT, "Apply").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(1) .back .img-responsive").click()
    self.driver.find_element(By.ID, "buttonCart").click()
    self.driver.find_element(By.LINK_TEXT, "Add to wishlist").click()
    self.driver.find_element(By.LINK_TEXT, "Change").click()
    self.driver.find_element(By.ID, "form-number").click()
    self.driver.find_element(By.ID, "form-number").send_keys("1")
    self.driver.find_element(By.ID, "form-street").click()
    self.driver.find_element(By.ID, "form-street").send_keys("1")
    self.driver.find_element(By.ID, "form-city").click()
    self.driver.find_element(By.ID, "form-city").send_keys("1")
    self.driver.find_element(By.ID, "form-post-code").click()
    self.driver.find_element(By.ID, "form-post-code").send_keys("1")
    self.driver.find_element(By.ID, "form-country").click()
    self.driver.find_element(By.ID, "form-country").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, "#form-address .btn").click()
    self.driver.execute_script("window.scrollTo(0,300)")
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-6:nth-child(2) > .box a").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".col-md-6:nth-child(2) > .box a")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "form-card-number").click()
    self.driver.find_element(By.ID, "form-card-number").send_keys("1")
    self.driver.find_element(By.ID, "form-expires").click()
    self.driver.find_element(By.ID, "form-expires").send_keys("1")
    self.driver.find_element(By.ID, "form-ccv").click()
    self.driver.find_element(By.ID, "form-ccv").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, ".text-right > .btn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".text-right > .btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#card-modal .close").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pull-left > .btn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".dropdown-toggle")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".hidden-xs")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(3) .back .img-responsive").click()
    self.driver.find_element(By.ID, "buttonCart").click()
    self.driver.find_element(By.LINK_TEXT, "Add to wishlist").click()
    self.driver.find_element(By.LINK_TEXT, "Update basket").click()
  
