# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestproductbrowsing():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testproductbrowsing(self):
    self.driver.get("http://127.0.0.1:8080/index.html")
    self.driver.set_window_size(1048, 746)
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-toggle").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox:nth-child(1) input").click()
    self.driver.find_element(By.LINK_TEXT, "Apply").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox:nth-child(2) input").click()
    self.driver.find_element(By.LINK_TEXT, "Apply").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox:nth-child(3) input").click()
    self.driver.find_element(By.LINK_TEXT, "Apply").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(1) > ul:nth-child(2) > li:nth-child(1) > a")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox:nth-child(4) input").click()
    self.driver.find_element(By.LINK_TEXT, "Apply").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox:nth-child(5) input").click()
    self.driver.find_element(By.LINK_TEXT, "Apply").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox:nth-child(6) input").click()
    self.driver.find_element(By.LINK_TEXT, "Apply").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox:nth-child(7) input").click()
    self.driver.find_element(By.LINK_TEXT, "Apply").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox:nth-child(8) input").click()
    self.driver.find_element(By.LINK_TEXT, "Apply").click()
    element = self.driver.find_element(By.LINK_TEXT, "Apply")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox:nth-child(9) > label").click()
    self.driver.find_element(By.LINK_TEXT, "Apply").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox:nth-child(10) > label").click()
    self.driver.find_element(By.LINK_TEXT, "Apply").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox:nth-child(11) > label").click()
    self.driver.find_element(By.LINK_TEXT, "Apply").click()
    self.driver.find_element(By.LINK_TEXT, "9").click()
    self.driver.find_element(By.LINK_TEXT, "3").click()
    self.driver.find_element(By.NAME, "sort-by").click()
    dropdown = self.driver.find_element(By.NAME, "sort-by")
    dropdown.find_element(By.XPATH, "//option[. = 'Name']").click()
    self.driver.find_element(By.NAME, "sort-by").click()
    dropdown = self.driver.find_element(By.NAME, "sort-by")
    dropdown.find_element(By.XPATH, "//option[. = 'Sales first']").click()
    self.driver.find_element(By.LINK_TEXT, "Apply").click()
    self.driver.find_element(By.NAME, "sort-by").click()
    dropdown = self.driver.find_element(By.NAME, "sort-by")
    dropdown.find_element(By.XPATH, "//option[. = 'Name']").click()
    self.driver.find_element(By.LINK_TEXT, "Apply").click()
    self.driver.find_element(By.NAME, "sort-by").click()
    dropdown = self.driver.find_element(By.NAME, "sort-by")
    dropdown.find_element(By.XPATH, "//option[. = 'Name']").click()
    self.driver.find_element(By.LINK_TEXT, "6").click()
    self.driver.find_element(By.LINK_TEXT, "2").click()
    self.driver.find_element(By.LINK_TEXT, "Magic").click()
    self.driver.find_element(By.LINK_TEXT, "Sport").click()
    self.driver.find_element(By.LINK_TEXT, "Action").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(1) .back .img-responsive").click()
    self.driver.find_element(By.CSS_SELECTOR, ".back .img-responsive").click()
    self.driver.find_element(By.LINK_TEXT, "Catalogue").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(4) .back .img-responsive").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(1) .back .img-responsive").click()
  
